// Generated by Dart Safe Data Class Generator. * Change this header on extension settings *
// ignore_for_file: type=lint
import 'package:badges/badges.dart';
import 'package:flutter/material.dart';

import 'package:flutter_cakery_shop_ui/screen/cart_provider.dart';

import 'package:flutter_screenutil/flutter_screenutil.dart';

import 'package:flutter_cakery_shop_ui/data/cake.dart';
import 'package:flutter_cakery_shop_ui/screen/cart_view.dart';
import 'package:provider/provider.dart';
import 'package:badges/badges.dart' as badges_pkg;

class NavbarWidgetDrink extends StatelessWidget {
  const NavbarWidgetDrink({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BottomAppBar(
      clipBehavior: Clip.antiAlias,
      shape: const CircularNotchedRectangle(),
      notchMargin: 8,
      color: Colors.transparent,
      elevation: 10,
      child: Container(
        height: 50.0.h,
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.only(
            topLeft: Radius.circular(25.0.r),
            topRight: Radius.circular(25.0.r),
          ),
        ),
        child: Row(
          mainAxisAlignment: MainAxisAlignment.spaceBetween,
          children: [
            SizedBox(
              height: 50.0.h,
              width: MediaQuery.of(context).size.width / 2 - 40.0.w,
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: const [
                  Icon(
                    Icons.home,
                    color: Color(0xFFEF7532),
                  ),
                  Icon(
                    Icons.search,
                    color: Color(0xFF676E79),
                  )
                ],
              ),
            ),
            SizedBox(
              height: 50.0.h,
              width: MediaQuery.of(context).size.width / 2 - 40.0.w,
              child: Row(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: [
                  Consumer<CartProvider>(
                    builder: (_, cartProvider, __) => badges_pkg.Badge(
                      badgeContent: Text(
                        cartProvider.drinkCount.toString(),
                        style: TextStyle(color: Colors.white),
                      ),
                      showBadge: cartProvider.drinkCount > 0,
                      position: BadgePosition.topEnd(top: 0, end: 3),
                      child: IconButton(
                        icon: Icon(Icons.add_shopping_cart_rounded),
                        onPressed: () {
                          Navigator.of(context).push(MaterialPageRoute(
                            builder: (_) => CartScreen(),
                          ));
                        },
                      ),
                    ),
                  ),
                  const Icon(
                    Icons.person_outline,
                    color: Color(0xFF676E79),
                  )
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// class ProductListScreen extends StatelessWidget {
//   final List<Cake> cake;
//   const ProductListScreen({
//     Key? key,
//     required this.cake,
//   }) : super(key: key);

//   @override
//   Widget build(BuildContext context) {
//     return Scaffold(
//       appBar: AppBar(
//         title: Text('Daftar Produk'),
//         actions: [
//           Consumer<CartProvider>(
//             builder: (_, cartProvider, __) => badges_pkg.Badge(
//               badgeContent: Text(
//                 cartProvider.itemCount.toString(),
//                 style: TextStyle(color: Colors.white),
//               ),
//               showBadge: cartProvider.itemCount > 0,
//               position: BadgePosition.topEnd(top: 0, end: 3),
//               child: IconButton(
//                 icon: Icon(Icons.shopping_bag_outlined),
//                 onPressed: () {
//                   Navigator.of(context).push(MaterialPageRoute(
//                     builder: (_) => CartScreen(),
//                   ));
//                 },
//               ),
//             ),
//           ),
//         ],
//       ),
//       body: ListView.builder(
//         itemCount: cake.length,
//         itemBuilder: (context, index) {
//           final product = cake[index];
//           return ListTile(
//             title: Text(product.name),
//             subtitle: Text('Harga: ${product.price}'),
//             onTap: () {
//               Navigator.of(context).push(
//                 MaterialPageRoute(
//                   builder: (_) => ProductDetailScreen(product),
//                 ),
//               );
//             },
//           );
//         },
//       ),
//     );
//   }
// }
